#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/uhurufs_gateway
LOG_DIR=/var/vcap/sys/log/uhurufs_gateway
JOB_DIR=/var/vcap/jobs/uhurufs_gateway

PIDFILE=$RUN_DIR/uhurufs_gateway.pid

<%
lifecycle = properties.service_lifecycle
%>

<% if lifecycle and lifecycle.nfs_server %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
MT_OPTS="-t nfs"
MT_EXPORT=<%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "UhuruFS gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    <% if lifecycle and lifecycle.nfs_server %>
    mkdir -p $SNAPSHOT_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$SNAPSHOT_DIR"
    <% end %>

    exec /var/vcap/packages/uhurufs_gateway/services/uhurufs/bin/uhurufs_gateway \
         -c $JOB_DIR/config/uhurufs_gateway.yml \
         >>$LOG_DIR/uhurufs_gateway.stdout.log \
         2>>$LOG_DIR/uhurufs_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    <% if lifecycle and lifecycle.nfs_server %>
    umount $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: uhurufs_gateway_ctl {start|stop}"

    ;;

esac
