#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH
RUN_DIR=/var/vcap/sys/run/uhuru_webui
LOG_DIR=/var/vcap/sys/log/uhuru_webui
PIDFILE=$RUN_DIR/uhuru_webui.pid
JOB_DIR=/var/vcap/jobs/uhuru_webui

source /var/vcap/packages/common/utils.sh


case $1 in

  start)
    pid_guard $PIDFILE "Uhuru WebUI"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    export CONFIG_FILE=$JOB_DIR/config/uhuru-webui.yml

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    cd /var/vcap/packages/uhuru_webui

    exec /var/vcap/packages/ruby/bin/ruby \
         /var/vcap/packages/uhuru_webui/main.rb \
         >>$LOG_DIR/uhuru_webui.stdout.log \
         2>>$LOG_DIR/uhuru_webui.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: uhuru_webui_ctl {start|stop}"

    ;;

esac
