source 'https://rubygems.org'

gem "blobstore_client", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '66eec1b4b64d144288e395e734ce03e64b6d87cc'
gem "bosh_cli", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '66eec1b4b64d144288e395e734ce03e64b6d87cc'
gem "uhuru-publisher", :git => "git@github.com:UhuruSoftware/private-uhuru-commander.git"

