---
product: appcloudng
type: alpha
releases:
  - name: appcloudng.core
    tarball: core.release
    path: '.'
  - name: appcloudng.services
    tarball: services.release
    path: cf-services-release
    git_repo: https://github.com/cloudfoundry/cf-services-release.git
  - name: appcloudng.services-contrib
    tarball: services-contrib.release
    path: cf-services-contrib-release
    git_repo: git@github.com:UhuruSoftware/cf-services-contrib-release.git
  - name: appcloudng.uhuru-service
    tarball: uhuru-services.release
    path: private-uhuru-services-release
    git_repo: ssh://jenkins@gerrit.uhurusoftware.org:29418/private-uhuru-services-release
 

