---
keys:
  '["properties"]["postgresql_gateway"]["token"]': '["properties"]["postgresql_gateway"]["token"]'
  '["properties"]["rabbit_gateway"]["token"]': '["properties"]["rabbit_gateway"]["token"]'
  '["properties"]["mongodb_gateway"]["token"]': '["properties"]["mongodb_gateway"]["token"]'
  '["properties"]["redis_gateway"]["token"]': '["properties"]["redis_gateway"]["token"]'
  '["properties"]["mysql_gateway"]["token"]': '["properties"]["mysql_gateway"]["token"]'
  '["properties"]["mssql_gateway"]["token"]': '["properties"]["mssql_gateway"]["token"]'
  '["properties"]["uhurufs_gateway"]["token"]': '["properties"]["uhurufs_gateway"]["token"]'
  '["properties"]["router"]["status"]["user"]': '["properties"]["router"]["status"]["user"]'
  '["properties"]["router"]["status"]["password"]': '["properties"]["router"]["status"]["password"]'
  '["properties"]["vcap_redis"]["password"]': '["properties"]["vcap_redis"]["password"]'
  '["properties"]["cc"]["password"]': '["properties"]["cc"]["password"]'
  '["properties"]["cc"]["token"]': '["properties"]["cc"]["token"]'
  '["properties"]["cc"]["staging_upload_user"]': '["properties"]["cc"]["staging_upload_user"]'
  '["properties"]["cc"]["staging_upload_password"]': '["properties"]["cc"]["staging_upload_password"]'
  '["properties"]["cc"]["bootstrap_users"].select{|u| u["email"] == "simplewebui@uhurudaemon.org"}.first["password"]': '["properties"]["cc"]["bootstrap_users"].select{|u| u["email"] == "simplewebui@uhurudaemon.org"}.first["password"]'
  '["properties"]["ccdb"]["roles"].select{|r| r["tag"] == "admin"}.first["password"]': '["properties"]["ccdb"]["roles"].select{|r| r["tag"] == "admin"}.first["password"]'
  '["properties"]["ccdb"]["roles"].select{|r| r["tag"] == "monitoring"}.first["password"]': '["properties"]["ccdb"]["roles"].select{|r| r["tag"] == "monitoring"}.first["password"]'
  '["properties"]["ccdb"]["databases"].select{|r| r["tag"] == "cc"}.first["name"]': '["properties"]["ccdb"]["databases"].select{|r| r["tag"] == "cc"}.first["name"]'
  '["properties"]["ccdb"]["dbname"]': '["properties"]["ccdb"]["dbname"]'
  '["properties"]["ccdb"]["password"]': '["properties"]["ccdb"]["password"]'
  '["properties"]["nats"]["user"]': '["properties"]["nats"]["user"]'
  '["properties"]["nats"]["password"]': '["properties"]["nats"]["password"]'
  '["properties"]["uhuru"]["simple_webui"]["activation_link_secret"]': '["properties"]["uhuru"]["simple_webui"]["activation_link_secret"]'
  '["properties"]["uhuru"]["simple_webui"]["default_random_password"]': '["properties"]["uhuru"]["simple_webui"]["default_random_password"]'
  '["properties"]["uhuru"]["simple_webui"]["monitoring"]["cloud_password"]': '["properties"]["uhuru"]["simple_webui"]["monitoring"]["cloud_password"]'
  '["properties"]["uhuru"]["simple_webui"]["admin_password"]': '["properties"]["uhuru"]["simple_webui"]["admin_password"]'
  '["properties"]["mysql_node"]["password"]': '["properties"]["mysql_node"]["password"]'